### ISSUE TITLE
Books: Planning

### ISSUE THREAD

**Issue by ludmilamarian** [CERNDocumentServer/cds-books#5]
### [63d] Backend
- [x] [2d] handle `_access` on documents/items
- [ ] [15d][not core] Calendar functionality
- [x] [10d][not core] Statistics - page views
- [ ] [2d][later] Integrate final data model
- [ ] [15d][core] Files storage -> add, update, remove files
- [x] [5d][not core] Email notifications: reminders and updates
- [x] [5d] **CDS Overlay** bootstrap and ILS integration
- [x] [2d][core] **CDS Overlay** CERN Oauth for authentication
- [x] [1d] **CDS Overlay** E-groups for permissions
- [ ] [10d][not core]  **CDS Overlay** Amazon harvester
- [x] [4d][not core]  **CDS Overlay** EDH termination sheet

### [75d] UI
- [x] [25d] Back office UI
    - [x] Librarian can create a Loan for user
    - [x] Librarian can manage Loan requests
    - [x] Librarian performs loan return or extend 
    - [x] Librarian can see Loan information (individual loan, loan history, etc.)
    - Librarian can search with facets
- [x] [5d] Search with facets
- [ ] [10d] Better homepage
- [ ] [10d] Better details page: request loan, available copies, e-books
- [x] [15d] Authenticated views: user/loans pages, user cancels loan, history
- [x] [3d] Better webpack build
- [x] [20d] Invenio Search UI
- [ ] [5d] **CDS Overlay** logo/about/faq/help pages
- [ ] [5d] **CDS Overlay** sharing/basic SEO

~~## [1W] Circulation~~
- Enhance search class methods by addressing these issues
    - [x] https://github.com/inveniosoftware/invenio-circulation/issues/18
    - [x] https://github.com/inveniosoftware/invenio-circulation/issues/19
    - [x] https://github.com/inveniosoftware/invenio-circulation/issues/20

## [25d] Acquisition
- [ ] The backend should be implemented and should be plugged in with the ils backend and ui
- [ ] migrate data

## [25d] ILL
- [ ] The backend should be implemented and should be plugged in with the ils backend and ui
- [ ] migrate data

### [20d] Migration of records 
- [x] cleaning schemas and managing different document types within one big schema
- [ ] implement new rules according to the needs of Library (fields to be decided about how to migrate, some discoveries during cleaning the data)
- [ ] implementing the actual migration (db configuration, move and reorganise the migration code - it is written in cds-dojson)
- [ ] reorganizing the rest of the code in [cds-dojson](https://github.com/CERNDocumentServer/cds-dojson) and [cds-migrator-kit](https://github.com/CERNDocumentServer/cds-migrator-kit) repositories

### [5d] Migration of circulation data
- [ ] migrate loans
- [x] migrate users

### [15d] Migration of items
- [x] migrate the items
- [x] migrate the volumes

## [10d] Invenio Record Editor
- [x] Pass custom configuration from invenio instance to the angular editor.
- [x] Display problems if any when edited record is not valid.
- [x] Test it with an actual invenio instance i.e. ILS
- [ ] handle references

## [5d] Infrastructure
- [x] OpenShift
- [x] ESoD vs ES (fix branch in invenio-search)

## [0] Testing
- [x] List test scenarios, ensuring all requirements are taken into account

## Nice to have
- [ ] way to copy data between `prod` and `pre-prod`
