### ISSUE TITLE
ldap: enhance tasks

### ISSUE THREAD

**Issue by zzacharo** [CERNDocumentServer/cds-books#59]
The sync of CERN users with LDAP should run every day and it can succeed or fail. Currently it is only a CLI command executed when needed.
It would be nice to display the task executions in the Invenio Admin interface, so that admins can immediately check status and see errors.

### Tasks

- [x] refactor the CLI command `sync_users` to be a dedicated function that can be called on demand by the existing CLI command or a cron task
- [x] create a cron task to run every night and execute this sync
- [x] refactor the code to print very clear console messages in a structure way (JSON logging) so that such logs can be eventually sent to Elasticsearch and we can run queries on it (see example in InvenioILS `ReferencedRecordsIndexer`). Ensure that exceptions are sent to `Sentry` (normally it is automatically happening when using console.error or console.exception, to be checked), please test it
- [x] create a new db table to store information of each task execution, one row per task exec. Each time the function is run, by a celery task or manually via CLI, it should report at least (db columns):
  - agent (or similar): CLI or celery cron (choose appropriate naming)
  - task id, if celery cron
  - status: RUNNING/SUCCEEDED/FAILED
  - message: might be a report message if running, e.g. fetching users, and the error message (stacktrace or not?) if error
  - start datetime
  - end datetime
  - how many CERN users fetched from LDAP
  - how many users updated in ILS (because some fields changed)
  - how many users deleted from ILS
  - how many users added in ILS
  - any other field?
- [x] create an admin panel in `invenio-admin` to display these rows. Add a button to trigger a new celery task on demand.
