### ISSUE TITLE
Document schema extra data

### ISSUE THREAD

**Issue by ntarocco** [CERNDocumentServer/cds-books#82]
Don't forget to add any CDS-specific changes in the schemas.

F.e: Document schema
Define the `extra_data` properties in the schema with the library:
* `experiment`
* `department`
* standard -> applicable to CERN

Implementation in RDM: https://github.com/inveniosoftware/invenio-rdm-records/pull/75

Tasks
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/878
- [x] https://github.com/inveniosoftware/invenio-app-ils-ui/issues/8
- [x] add cds-books configuration #98

**Comment by kprzerwa** [comment]
```
"accelerator_experiments": {
      "description": ":MARC: 693\n.. note:: Modified from Inspire: add 693__s, 693__p and not link to experiment record\n",
      "items": {
        "additionalProperties": false,
        "properties": {
          "accelerator": {
            "description": ":MARC: ``693__a``\nIf present, :ref:`institution` should contain the\ninstitution where this accelerator is located.\n.. note::\n    Currently not used, see :ref:`legacy_name`.",
            "minLength": 1,
            "type": "string"
          },
          "curated_relation": {
            "default": false,
            "type": "boolean"
          },
          "experiment": {
            "description": "If present, :ref:`institution` should contain the\ninstitution where this experiment is located and\n:ref:`accelerator` may contain the accelerator that this\nexperiment is using (if appropriate).\n.. note::\n    Currently not used, see :ref:`legacy_name`.",
            "minLength": 1,
            "type": "string"
          },
          "institution": {
            "description": ":MARC: not present.\n.. note::\n    Currently not used, see :ref:`legacy_name`.",
            "minLength": 1,
            "title": "Institution hosting the experiment",
            "type": "string"
          },
          "legacy_name": {
            "description": ":MARC: ``693__e``\nThis field is used when migrating from legacy instead\nof separate :ref:`institution`, :ref:`accelerator` and\n:ref:`experiment`. In the future, it will be deprecated and\nthe other fields will be used instead.\n:example: ``CERN-LHC-CMS``",
            "minLength": 1,
            "title": "Identifier of the experiment on legacy",
            "type": "string"
          },
          "project": {
            "description": ":MARC: 693__p",
            "minLength": 1,
            "title": "Project",
            "type": "string"
          },
          "study": {
            "description": ":MARC: 693__s",
            "minLength": 1,
            "title": "Study",
            "type": "string"
          }
        },
        "type": "object"
      },
      "minItems": 1,
      "title": "List of related accelerators/experiments/study/project",
      "type": "array",
      "uniqueItems": true
    },
```

AND

```
standard_CERN_status:
 description: 'MARC: No MARC'
 	.. Note:: Used for Standards only.
 items:
  additionalProperties: false
  properties:
    CERN_applicability:
      description: Indicates if the standard is applicable at CERN
      enum:
       - applicable
       - no yet applicable
       - no longer applicable
      minLength: 1
      title: Applicability at CERN
      type: string          
    standard_validity:
      description: Status of the standard
      enum:
       - published
       - withdrawn
       - under development
       - not yet published
      minLength: 1
      title: Standard status
      type: string    
    check_date:
      description: Date of the expert checking
      format: date
      minLength: 1
      type: string
    comment:
      description: Comment of the expert
      minLength: 1
      type: string
    expert:
      description: Expert name
      minLength: 1
      type: string
 required:
   - standard_validtity
 type: array
 uniqueItems: true

``` 

see https://github.com/CERNDocumentServer/cds-dojson/issues/219
and https://github.com/CERNDocumentServer/cds-dojson/blob/books-schema/cds_dojson/schemas/records/books/book/document-v0.0.1.json
```
