### ISSUE TITLE
CERN overlay

### ISSUE THREAD

**Issue by ntarocco** [CERNDocumentServer/cds-books#97]
- [ ] Override default configuration and set the value for CDS Books: https://github.com/CERNDocumentServer/cds-books/issues/80
- [x] Define and enhance the delivery method UX: https://github.com/CERNDocumentServer/cds-books/issues/30
- [x] Change facets: https://github.com/CERNDocumentServer/cds-books/issues/9
- [x] Integrate CERN Theme (see attachment [ILS-homepage.pdf](https://github.com/CERNDocumentServer/cds-books/files/4568026/ILS-homepage.pdf)) https://github.com/CERNDocumentServer/cds-books/issues/101
- [x] CERN custom fields
- [x] background photo (see [here](https://cds.cern.ch/record/2693789?ln=en))
- [x] show "CDS branding" somehow in the header
